void jsonnew() {
  dados = new JSONObject();
  dados.setString("Endereço", "");
  dados.setString("Campus", "");
  dados.setString("Bloco", "");
  dados.setString("Sala", "");
  dados.setString("BairroDistrito", "");
  dados.setString("Cidade", "");
  dados.setString("CEP", "");
  dados.setString("Telefone", "");
  dados.setString("Ramal", "");
  dados.setString("Email", "");
  dados.setString("ID", "");
  dados.setString("Chamado", "");
  dados.setString("Contrato", "");
  dados.setString("Contato", "");
  dados.setString("Responsavel", "");
  dados.setString("Ma1", "");
  dados.setString("Cl1", "");
  dados.setString("Eq1", "");
  dados.setString("Mo1", "");
  dados.setString("Sn1", "");
  dados.setString("Ve1", "");
  dados.setString("Ma2", "");
  dados.setString("Cl2", "");
  dados.setString("Eq2", "");
  dados.setString("Mo2", "");
  dados.setString("Sn2", "");
  dados.setString("Ve2", "");
  dados.setString("Ma3", "");
  dados.setString("Cl3", "");
  dados.setString("Eq3", "");
  dados.setString("Mo3", "");
  dados.setString("Sn3", "");
  dados.setString("Ve3", "");
  dados.setString("Ma4", "");
  dados.setString("Cl4", "");
  dados.setString("Eq4", "");
  dados.setString("Mo4", "");
  dados.setString("Sn4", "");
  dados.setString("Ve4", "");
  dados.setString("Ma5", "");
  dados.setString("Cl5", "");
  dados.setString("Eq5", "");
  dados.setString("Mo5", "");
  dados.setString("Sn5", "");
  dados.setString("Ve5", "");
  dados.setString("Ma6", "");
  dados.setString("Cl6", "");
  dados.setString("Eq6", "");
  dados.setString("Mo6", "");
  dados.setString("Sn6", "");
  dados.setString("Ve6", "");
  dados.setString("Data1", "");
  dados.setString("DeslT1", "");
  dados.setString("DeslA1", "");
  dados.setString("HorT1", "");
  dados.setString("Diver1", "");
  dados.setString("Total1", "");
  dados.setString("Data2", "");
  dados.setString("DeslT2", "");
  dados.setString("DeslA2", "");
  dados.setString("HorT2", "");
  dados.setString("Diver2", "");
  dados.setString("Total2", "");
  dados.setString("Data3", "");
  dados.setString("DeslT3", "");
  dados.setString("DeslA3", "");
  dados.setString("HorT3", "");
  dados.setString("Diver3", "");
  dados.setString("Total3", "");
  dados.setString("Data4", "");
  dados.setString("DeslT4", "");
  dados.setString("DeslA4", "");
  dados.setString("HorT4", "");
  dados.setString("Diver4", "");
  dados.setString("Total4", "");
  dados.setString("Data5", "");
  dados.setString("DeslT5", "");
  dados.setString("DeslA5", "");
  dados.setString("HorT5", "");
  dados.setString("Diver5", "");
  dados.setString("Total5", "");
  dados.setString("Pedido1", "");
  dados.setString("ContrPc1", "");
  dados.setString("Item1", "");
  dados.setString("Descr1", "");
  dados.setString("Quantid1", "");
  dados.setString("Detalhe1", "");
  dados.setString("Pedido2", "");
  dados.setString("ContrPc2", "");
  dados.setString("Item2", "");
  dados.setString("Descr2", "");
  dados.setString("Quantid2", "");
  dados.setString("Detalhe2", "");
  dados.setString("Pedido3", "");
  dados.setString("ContrPc3", "");
  dados.setString("Item3", "");
  dados.setString("Descr3", "");
  dados.setString("Quantid3", "");
  dados.setString("Detalhe3", "");
  dados.setString("Pedido4", "");
  dados.setString("ContrPc4", "");
  dados.setString("Item4", "");
  dados.setString("Descr4", "");
  dados.setString("Quantid4", "");
  dados.setString("Detalhe4", "");
  dados.setString("Pedido5", "");
  dados.setString("ContrPc5", "");
  dados.setString("Item5", "");
  dados.setString("Descr5", "");
  dados.setString("Quantid5", "");
  dados.setString("Detalhe5", "");
  dados.setString("Relatorio", "");
  dados.setString("Historico", "");
}

void jsonex() {
  endereco.setText(getConfigurationString("Endereço"));
  campus.setText(getConfigurationString("Campus"));
  bloco.setText(getConfigurationString("Bloco"));
  sala.setText(getConfigurationString("Sala"));
  bairrodistrito.setText(getConfigurationString("BairroDistrito"));
  cidade.setText(getConfigurationString("Cidade"));
  cep.setText(getConfigurationString("CEP"));
  telefone.setText(getConfigurationString("Telefone"));
  ramal.setText(getConfigurationString("Ramal"));
  email.setText(getConfigurationString("Email"));
  id.setText(getConfigurationString("ID"));
  chamado.setText(getConfigurationString("Chamado"));
  contrato.setText(getConfigurationString("Contrato"));
  contato.setText(getConfigurationString("Contato"));
  responsavel.setText(getConfigurationString("Responsavel"));
  ma1.setText(getConfigurationString("Ma1"));
  cl1.setText(getConfigurationString("Cl1"));
  eq1.setText(getConfigurationString("Eq1"));
  mo1.setText(getConfigurationString("Mo1"));
  sn1.setText(getConfigurationString("Sn1"));
  ve1.setText(getConfigurationString("Ve1"));
  ma2.setText(getConfigurationString("Ma2"));
  cl2.setText(getConfigurationString("Cl2"));
  eq2.setText(getConfigurationString("Eq2"));
  mo2.setText(getConfigurationString("Mo2"));
  sn2.setText(getConfigurationString("Sn2"));
  ve2.setText(getConfigurationString("Ve2"));
  ma3.setText(getConfigurationString("Ma3"));
  cl3.setText(getConfigurationString("Cl3"));
  eq3.setText(getConfigurationString("Eq3"));
  mo3.setText(getConfigurationString("Mo3"));
  sn3.setText(getConfigurationString("Sn3"));
  ve3.setText(getConfigurationString("Ve3"));
  ma4.setText(getConfigurationString("Ma4"));
  cl4.setText(getConfigurationString("Cl4"));
  eq4.setText(getConfigurationString("Eq4"));
  mo4.setText(getConfigurationString("Mo4"));
  sn4.setText(getConfigurationString("Sn4"));
  ve4.setText(getConfigurationString("Ve4"));
  ma5.setText(getConfigurationString("Ma5"));
  cl5.setText(getConfigurationString("Cl5"));
  eq5.setText(getConfigurationString("Eq5"));
  mo5.setText(getConfigurationString("Mo5"));
  sn5.setText(getConfigurationString("Sn5"));
  ve5.setText(getConfigurationString("Ve5"));
  ma6.setText(getConfigurationString("Ma6"));
  cl6.setText(getConfigurationString("Cl6"));
  eq6.setText(getConfigurationString("Eq6"));
  mo6.setText(getConfigurationString("Mo6"));
  sn6.setText(getConfigurationString("Sn6"));
  ve6.setText(getConfigurationString("Ve6"));
  data1.setText(getConfigurationString("Data1"));
  deslT1.setText(getConfigurationString("DeslT1"));
  deslA1.setText(getConfigurationString("DeslA1"));
  horT1.setText(getConfigurationString("HorT1"));
  diver1.setText(getConfigurationString("Diver1"));
  total1.setText(getConfigurationString("Total1"));
  data2.setText(getConfigurationString("Data2"));
  deslT2.setText(getConfigurationString("DeslT2"));
  deslA2.setText(getConfigurationString("DeslA2"));
  horT2.setText(getConfigurationString("HorT2"));
  diver2.setText(getConfigurationString("Diver2"));
  total2.setText(getConfigurationString("Total2"));
  data3.setText(getConfigurationString("Data3"));
  deslT3.setText(getConfigurationString("DeslT3"));
  deslA3.setText(getConfigurationString("DeslA3"));
  horT3.setText(getConfigurationString("HorT3"));
  diver3.setText(getConfigurationString("Diver3"));
  total3.setText(getConfigurationString("Total3"));
  data4.setText(getConfigurationString("Data4"));
  deslT4.setText(getConfigurationString("DeslT4"));
  deslA4.setText(getConfigurationString("DeslA4"));
  horT4.setText(getConfigurationString("HorT4"));
  diver4.setText(getConfigurationString("Diver4"));
  total4.setText(getConfigurationString("Total4"));
  data5.setText(getConfigurationString("Data5"));
  deslT5.setText(getConfigurationString("DeslT5"));
  deslA5.setText(getConfigurationString("DeslA5"));
  horT5.setText(getConfigurationString("HorT5"));
  diver5.setText(getConfigurationString("Diver5"));
  total5.setText(getConfigurationString("Total5"));
  pedido1.setText(getConfigurationString("Pedido1"));
  contrPc1.setText(getConfigurationString("ContrPc1"));
  item1.setText(getConfigurationString("Item1"));
  descr1.setText(getConfigurationString("Descr1"));
  quantid1.setText(getConfigurationString("Quantid1"));
  detalhe1.setText(getConfigurationString("Detalhe1"));
  pedido2.setText(getConfigurationString("Pedido2"));
  contrPc2.setText(getConfigurationString("ContrPc2"));
  item2.setText(getConfigurationString("Item2"));
  descr2.setText(getConfigurationString("Descr2"));
  quantid2.setText(getConfigurationString("Quantid2"));
  detalhe2.setText(getConfigurationString("Detalhe2"));
  pedido3.setText(getConfigurationString("Pedido3"));
  contrPc3.setText(getConfigurationString("ContrPc3"));
  item3.setText(getConfigurationString("Item3"));
  descr3.setText(getConfigurationString("Descr3"));
  quantid3.setText(getConfigurationString("Quantid3"));
  detalhe3.setText(getConfigurationString("Detalhe3"));
  pedido4.setText(getConfigurationString("Pedido4"));
  contrPc4.setText(getConfigurationString("ContrPc4"));
  item4.setText(getConfigurationString("Item4"));
  descr4.setText(getConfigurationString("Descr4"));
  quantid4.setText(getConfigurationString("Quantid4"));
  detalhe4.setText(getConfigurationString("Detalhe4"));
  pedido5.setText(getConfigurationString("Pedido5"));
  contrPc5.setText(getConfigurationString("ContrPc5"));
  item5.setText(getConfigurationString("Item5"));
  descr5.setText(getConfigurationString("Descr5"));
  quantid5.setText(getConfigurationString("Quantid5"));
  detalhe5.setText(getConfigurationString("Detalhe5"));
  relat.setPromptText(getConfigurationString("Relatorio"));
  historico.setPromptText(getConfigurationString("Historico"));
}

void jsonset() {
  dados = new JSONObject();
  dados.setString("Endereço", cp1.get(Textfield.class, "Endereco").getText());
  dados.setString("Campus", cp1.get(Textfield.class, "Campus").getText());
  dados.setString("Bloco", cp1.get(Textfield.class, "Bloco").getText());
  dados.setString("Sala", cp1.get(Textfield.class, "Sala").getText());
  dados.setString("BairroDistrito", cp1.get(Textfield.class, "BairroDistrito").getText());
  dados.setString("Cidade", cp1.get(Textfield.class, "Cidade").getText());
  dados.setString("CEP", cp1.get(Textfield.class, "CEP").getText());
  dados.setString("Telefone", cp1.get(Textfield.class, "Telefone").getText());
  dados.setString("Ramal", cp1.get(Textfield.class, "Ramal").getText());
  dados.setString("Email", cp1.get(Textfield.class, "Email").getText());
  dados.setString("ID", cp1.get(Textfield.class, "ID").getText());
  dados.setString("Chamado", cp1.get(Textfield.class, "Chamado").getText());
  dados.setString("Contrato", cp1.get(Textfield.class, "Contrato").getText());
  dados.setString("Contato", cp1.get(Textfield.class, "Contato").getText());
  dados.setString("Responsavel", cp1.get(Textfield.class, "Responsavel").getText());
  dados.setString("Ma1", cp1.get(Textfield.class, "Ma1").getText());
  dados.setString("Cl1", cp1.get(Textfield.class, "Cl1").getText());
  dados.setString("Eq1", cp1.get(Textfield.class, "Eq1").getText());
  dados.setString("Mo1", cp1.get(Textfield.class, "Mo1").getText());
  dados.setString("Sn1", cp1.get(Textfield.class, "Sn1").getText());
  dados.setString("Ve1", cp1.get(Textfield.class, "Ve1").getText());
  dados.setString("Ma2", cp1.get(Textfield.class, "Ma2").getText());
  dados.setString("Cl2", cp1.get(Textfield.class, "Cl2").getText());
  dados.setString("Eq2", cp1.get(Textfield.class, "Eq2").getText());
  dados.setString("Mo2", cp1.get(Textfield.class, "Mo2").getText());
  dados.setString("Sn2", cp1.get(Textfield.class, "Sn2").getText());
  dados.setString("Ve2", cp1.get(Textfield.class, "Ve2").getText());
  dados.setString("Ma3", cp1.get(Textfield.class, "Ma3").getText());
  dados.setString("Cl3", cp1.get(Textfield.class, "Cl3").getText());
  dados.setString("Eq3", cp1.get(Textfield.class, "Eq3").getText());
  dados.setString("Mo3", cp1.get(Textfield.class, "Mo3").getText());
  dados.setString("Sn3", cp1.get(Textfield.class, "Sn3").getText());
  dados.setString("Ve3", cp1.get(Textfield.class, "Ve3").getText());
  dados.setString("Ma4", cp1.get(Textfield.class, "Ma4").getText());
  dados.setString("Cl4", cp1.get(Textfield.class, "Cl4").getText());
  dados.setString("Eq4", cp1.get(Textfield.class, "Eq4").getText());
  dados.setString("Mo4", cp1.get(Textfield.class, "Mo4").getText());
  dados.setString("Sn4", cp1.get(Textfield.class, "Sn4").getText());
  dados.setString("Ve4", cp1.get(Textfield.class, "Ve4").getText());
  dados.setString("Ma5", cp1.get(Textfield.class, "Ma5").getText());
  dados.setString("Cl5", cp1.get(Textfield.class, "Cl5").getText());
  dados.setString("Eq5", cp1.get(Textfield.class, "Eq5").getText());
  dados.setString("Mo5", cp1.get(Textfield.class, "Mo5").getText());
  dados.setString("Sn5", cp1.get(Textfield.class, "Sn5").getText());
  dados.setString("Ve5", cp1.get(Textfield.class, "Ve5").getText());
  dados.setString("Ma6", cp1.get(Textfield.class, "Ma6").getText());
  dados.setString("Cl6", cp1.get(Textfield.class, "Cl6").getText());
  dados.setString("Eq6", cp1.get(Textfield.class, "Eq6").getText());
  dados.setString("Mo6", cp1.get(Textfield.class, "Mo6").getText());
  dados.setString("Sn6", cp1.get(Textfield.class, "Sn6").getText());
  dados.setString("Ve6", cp1.get(Textfield.class, "Ve6").getText());
  dados.setString("Data1", cp1.get(Textfield.class, "Data1").getText());
  dados.setString("DeslT1", cp1.get(Textfield.class, "DeslT1").getText());
  dados.setString("DeslA1", cp1.get(Textfield.class, "DeslA1").getText());
  dados.setString("HorT1", cp1.get(Textfield.class, "HorT1").getText());
  dados.setString("Diver1", cp1.get(Textfield.class, "Diver1").getText());
  dados.setString("Total1", cp1.get(Textfield.class, "Total1").getText());
  dados.setString("Data2", cp1.get(Textfield.class, "Data2").getText());
  dados.setString("DeslT2", cp1.get(Textfield.class, "DeslT2").getText());
  dados.setString("DeslA2", cp1.get(Textfield.class, "DeslA2").getText());
  dados.setString("HorT2", cp1.get(Textfield.class, "HorT2").getText());
  dados.setString("Diver2", cp1.get(Textfield.class, "Diver2").getText());
  dados.setString("Total2", cp1.get(Textfield.class, "Total2").getText());
  dados.setString("Data3", cp1.get(Textfield.class, "Data3").getText());
  dados.setString("DeslT3", cp1.get(Textfield.class, "DeslT3").getText());
  dados.setString("DeslA3", cp1.get(Textfield.class, "DeslA3").getText());
  dados.setString("HorT3", cp1.get(Textfield.class, "HorT3").getText());
  dados.setString("Diver3", cp1.get(Textfield.class, "Diver3").getText());
  dados.setString("Total3", cp1.get(Textfield.class, "Total3").getText());
  dados.setString("Data4", cp1.get(Textfield.class, "Data4").getText());
  dados.setString("DeslT4", cp1.get(Textfield.class, "DeslT4").getText());
  dados.setString("DeslA4", cp1.get(Textfield.class, "DeslA4").getText());
  dados.setString("HorT4", cp1.get(Textfield.class, "HorT4").getText());
  dados.setString("Diver4", cp1.get(Textfield.class, "Diver4").getText());
  dados.setString("Total4", cp1.get(Textfield.class, "Total4").getText());
  dados.setString("Data5", cp1.get(Textfield.class, "Data5").getText());
  dados.setString("DeslT5", cp1.get(Textfield.class, "DeslT5").getText());
  dados.setString("DeslA5", cp1.get(Textfield.class, "DeslA5").getText());
  dados.setString("HorT5", cp1.get(Textfield.class, "HorT5").getText());
  dados.setString("Diver5", cp1.get(Textfield.class, "Diver5").getText());
  dados.setString("Total5", cp1.get(Textfield.class, "Total5").getText());
  dados.setString("Pedido1", cp1.get(Textfield.class, "Pedido1").getText());
  dados.setString("ContrPc1", cp1.get(Textfield.class, "ContrPc1").getText());
  dados.setString("Item1", cp1.get(Textfield.class, "Item1").getText());
  dados.setString("Descr1", cp1.get(Textfield.class, "Descr1").getText());
  dados.setString("Quantid1", cp1.get(Textfield.class, "Quantid1").getText());
  dados.setString("Detalhe1", cp1.get(Textfield.class, "Detalhe1").getText());
  dados.setString("Pedido2", cp1.get(Textfield.class, "Pedido2").getText());
  dados.setString("ContrPc2", cp1.get(Textfield.class, "ContrPc2").getText());
  dados.setString("Item2", cp1.get(Textfield.class, "Item2").getText());
  dados.setString("Descr2", cp1.get(Textfield.class, "Descr2").getText());
  dados.setString("Quantid2", cp1.get(Textfield.class, "Quantid2").getText());
  dados.setString("Detalhe2", cp1.get(Textfield.class, "Detalhe2").getText());
  dados.setString("Pedido3", cp1.get(Textfield.class, "Pedido3").getText());
  dados.setString("ContrPc3", cp1.get(Textfield.class, "ContrPc3").getText());
  dados.setString("Item3", cp1.get(Textfield.class, "Item3").getText());
  dados.setString("Descr3", cp1.get(Textfield.class, "Descr3").getText());
  dados.setString("Quantid3", cp1.get(Textfield.class, "Quantid3").getText());
  dados.setString("Detalhe3", cp1.get(Textfield.class, "Detalhe3").getText());
  dados.setString("Pedido4", cp1.get(Textfield.class, "Pedido4").getText());
  dados.setString("ContrPc4", cp1.get(Textfield.class, "ContrPc4").getText());
  dados.setString("Item4", cp1.get(Textfield.class, "Item4").getText());
  dados.setString("Descr4", cp1.get(Textfield.class, "Descr4").getText());
  dados.setString("Quantid4", cp1.get(Textfield.class, "Quantid4").getText());
  dados.setString("Detalhe4", cp1.get(Textfield.class, "Detalhe4").getText());
  dados.setString("Pedido5", cp1.get(Textfield.class, "Pedido5").getText());
  dados.setString("ContrPc5", cp1.get(Textfield.class, "ContrPc5").getText());
  dados.setString("Item5", cp1.get(Textfield.class, "Item5").getText());
  dados.setString("Descr5", cp1.get(Textfield.class, "Descr5").getText());
  dados.setString("Quantid5", cp1.get(Textfield.class, "Quantid5").getText());
  dados.setString("Detalhe5", cp1.get(Textfield.class, "Detalhe5").getText());
  dados.setString("Relatorio", relat.getText());
  dados.setString("Historico", historico.getText());
}
